version: "3"
services:
  postgres:
    image: postgres:11-alpine
    volumes:
      - ./tracker/tmp/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pg_password
  tracker:
    build:
      context: ./tracker
      dockerfile: Dockerfile
    volumes:
      - ./tracker:/tracker
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=pg_password
      - DATABASE_POOL=5
    depends_on:
      - postgres
  example_website:
    build:
      context: ./example-website
      dockerfile: Dockerfile
    volumes:
      - ./example-website:/example_website
    ports:
      - "3001:3000"
