default: &default
  adapter: postgresql
  encoding: utf8
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  pool: <%= ENV['DATABASE_POOL'] %>

development:
  <<: *default
  database: tracker_development

test:
  <<: *default
  database: tracker_test
